In [1]:
import os
import re 

import jsonlines
import pandas as pd
import polars as pl

from autogen_core.models import UserMessage
from autogen_agentchat.agents import AssistantAgent, UserProxyAgent
from autogen_agentchat.messages import TextMessage
from autogen_core import CancellationToken
from autogen_ext.models.ollama import OllamaChatCompletionClient

In [2]:
data_path       = f'../data'
# tables_path     = f'{data_path}/datasets/CAN/tables/tables_from10000_to15000'
# metadata_path   = f'{data_path}/datasets/CAN/metadata/metadata_from10000_to15000'
tables_path     = f'{data_path}/datasets/CAN/tables/tables_from0_to10000'
metadata_path   = f'{data_path}/datasets/CAN/metadata/metadata_from0_to10000'

candidates_path = f'{data_path}/outputs/candidate_joins.csv'

In [3]:
table_ids = list(sorted(os.listdir(tables_path), reverse=True))

In [4]:
with jsonlines.open(metadata_path) as fr:
    metadata = {rsc['id']: md for md in fr.iter() for rsc in md['resources'] if rsc['format'] == 'CSV'}

In [5]:
def get_package_id(rsc_id):
    rsc_id = re.sub(r'(_\d+)?.parquet$', '', table_ids[rsc_id])
    return metadata[rsc_id]['id']
    
def get_resource_metadata(rsc_id):
    rsc_id = re.sub(r'(_\d+)?.parquet$', '', table_ids[rsc_id])
    md = next(
        filter(
            lambda r: r['id'] == rsc_id, metadata[rsc_id]['resources']))
    return md['name'], metadata[rsc_id]['title'], metadata[rsc_id]['notes']

In [6]:
candidates = pl.read_csv(candidates_path)
candidates

shape: (79_516, 14)
┌──────────┬──────────┬──────────┬──────────┬───┬─────────────────┬────────────┬─────────┬─────────┐
│ r_tab_id ┆ s_tab_id ┆ r_col_id ┆ s_col_id ┆ … ┆ size_intersecti ┆ size_union ┆ jaccard ┆ overlap │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ on              ┆ ---        ┆ ---     ┆ ---     │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆   ┆ ---             ┆ i64        ┆ f64     ┆ f64     │
│          ┆          ┆          ┆          ┆   ┆ i64             ┆            ┆         ┆         │
╞══════════╪══════════╪══════════╪══════════╪═══╪═════════════════╪════════════╪═════════╪═════════╡
│ 0        ┆ 7632     ┆ 0        ┆ 0        ┆ … ┆ 9               ┆ 11         ┆ 0.818   ┆ 1.0     │
│ 0        ┆ 7218     ┆ 0        ┆ 0        ┆ … ┆ 9               ┆ 11         ┆ 0.818   ┆ 1.0     │
│ 0        ┆ 5094     ┆ 0        ┆ 0        ┆ … ┆ 5               ┆ 18         ┆ 0.278   ┆ 0.455   │
│ 0        ┆ 5536     ┆ 0        ┆ 0        ┆ … ┆ 5               ┆ 18         ┆ 0.278   ┆ 0.455   │
│ 0        ┆ 94       ┆ 0        ┆ 0        ┆ … ┆ 4               ┆ 20         ┆ 0.2     ┆ 0.364   │
│ …        ┆ …        ┆ …        ┆ …        ┆ … ┆ …               ┆ …          ┆ …       ┆ …       │
│ 8835     ┆ 7577     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 5846     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 8246     ┆ 1        ┆ 0        ┆ … ┆ 25              ┆ 56         ┆ 0.446   ┆ 1.0     │
│ 8835     ┆ 5520     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 6482     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
└──────────┴──────────┴──────────┴──────────┴───┴─────────────────┴────────────┴─────────┴─────────┘

In [9]:
final_candidates = candidates
    # .filter(10 <= pl.col('size_r_col')) \
    # .filter(10 <= pl.col('size_s_col'))
    # .filter(pl.col('r_col_name') != pl.col('s_col_name')) \
    # .filter(10 <= pl.col('size_intersection')) \

final_candidates

shape: (79_516, 14)
┌──────────┬──────────┬──────────┬──────────┬───┬─────────────────┬────────────┬─────────┬─────────┐
│ r_tab_id ┆ s_tab_id ┆ r_col_id ┆ s_col_id ┆ … ┆ size_intersecti ┆ size_union ┆ jaccard ┆ overlap │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ on              ┆ ---        ┆ ---     ┆ ---     │
│ i64      ┆ i64      ┆ i64      ┆ i64      ┆   ┆ ---             ┆ i64        ┆ f64     ┆ f64     │
│          ┆          ┆          ┆          ┆   ┆ i64             ┆            ┆         ┆         │
╞══════════╪══════════╪══════════╪══════════╪═══╪═════════════════╪════════════╪═════════╪═════════╡
│ 0        ┆ 7632     ┆ 0        ┆ 0        ┆ … ┆ 9               ┆ 11         ┆ 0.818   ┆ 1.0     │
│ 0        ┆ 7218     ┆ 0        ┆ 0        ┆ … ┆ 9               ┆ 11         ┆ 0.818   ┆ 1.0     │
│ 0        ┆ 5094     ┆ 0        ┆ 0        ┆ … ┆ 5               ┆ 18         ┆ 0.278   ┆ 0.455   │
│ 0        ┆ 5536     ┆ 0        ┆ 0        ┆ … ┆ 5               ┆ 18         ┆ 0.278   ┆ 0.455   │
│ 0        ┆ 94       ┆ 0        ┆ 0        ┆ … ┆ 4               ┆ 20         ┆ 0.2     ┆ 0.364   │
│ …        ┆ …        ┆ …        ┆ …        ┆ … ┆ …               ┆ …          ┆ …       ┆ …       │
│ 8835     ┆ 7577     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 5846     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 8246     ┆ 1        ┆ 0        ┆ … ┆ 25              ┆ 56         ┆ 0.446   ┆ 1.0     │
│ 8835     ┆ 5520     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
│ 8835     ┆ 6482     ┆ 1        ┆ 3        ┆ … ┆ 25              ┆ 27         ┆ 0.926   ┆ 1.0     │
└──────────┴──────────┴──────────┴──────────┴───┴─────────────────┴────────────┴─────────┴─────────┘

Get an example row

In [58]:
i = 10

row = final_candidates.row(i)
r_tab_id, s_tab_id, r_col_id, s_col_id, r_col_name, s_col_name = row[:6]
row

(10,
 4945,
 1,
 0,
 'GEO',
 'Number of temporary foreign worker (TFW) positions on requested Labour Market Impact Assessments (LMIAs) by province/territory',
 14,
 23,
 'a93bf95b-3f04-4a00-8457-a12c62d1279a',
 'e8745429-21e7-4a73-b3f5-90a779b78d1e',
 14,
 23,
 0.609,
 1.0)

In [59]:
r_rsc_name, r_pkg_name, r_pkg_note = get_resource_metadata(r_tab_id)
s_rsc_name, s_pkg_name, s_pkg_note = get_resource_metadata(s_tab_id)

import re
r_pkg_note = re.sub(r"(\n|\r|\t)", " ", r_pkg_note)
s_pkg_note = re.sub(r"(\n|\r|\t)", " ", s_pkg_note)

print(f'> {r_rsc_name=}')
print(f'> {s_rsc_name=}')
print(f'>> {r_col_id=}')
print(f'>> {s_col_id=}')
print(f'>>> {r_col_name=}')
print(f'>>> {s_col_name=}')
print(f'>>>> {r_pkg_note[:500]=}')
print(f'>>>> {s_pkg_note[:500]=}')

> r_rsc_name='Dataset'
> s_rsc_name='Table 12-Number of Temporary Foreign Worker (TFW) Positions on Requested Labour Market Impact Assessments (LMIAs) by Province/Territory between 2023Q1 and 2024Q3'
>> r_col_id=1
>> s_col_id=0
>>> r_col_name='GEO'
>>> s_col_name='Number of temporary foreign worker (TFW) positions on requested Labour Market Impact Assessments (LMIAs) by province/territory'
>>>> r_pkg_note[:500]='Average weekly earnings (including overtime) for all employees by enterprise size and North American Industry Classification System (NAICS), last 5 quarters.'
>>>> s_pkg_note[:500]='Overview:    Each quarter, the Temporary Foreign Worker Program (TFWP) publishes Labour Market Impact Assessment (LMIA) statistics on Open Government Data Portal, including quarterly and annual LMIA data related to, but not limited to, requested and approved TFW positions, employment location, employment occupations, sectors, TFWP stream and temporary foreign workers by country of origin.  The TFWP does not collect data on the number of TFWs who are hired by an employer and have arrived in Canad'

In [60]:
r_df = pl.read_parquet(f'{tables_path}/{table_ids[r_tab_id]}')
r_df

shape: (307_230, 16)
┌──────────────┬─────────┬─────────────┬─────────────┬───┬────────┬────────┬────────────┬──────────┐
│ ï»¿"REF_DATE ┆ GEO     ┆ DGUID       ┆ Enterprise  ┆ … ┆ STATUS ┆ SYMBOL ┆ TERMINATED ┆ DECIMALS │
│ "            ┆ ---     ┆ ---         ┆ size of     ┆   ┆ ---    ┆ ---    ┆ ---        ┆ ---      │
│ ---          ┆ str     ┆ str         ┆ employment  ┆   ┆ str    ┆ f64    ┆ f64        ┆ i64      │
│ str          ┆         ┆             ┆ ---         ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ str         ┆   ┆        ┆        ┆            ┆          │
╞══════════════╪═════════╪═════════════╪═════════════╪═══╪════════╪════════╪════════════╪══════════╡
│ 2001-01      ┆ Canada  ┆ 2021A000011 ┆ All sizes   ┆ … ┆ null   ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆ 124         ┆             ┆   ┆        ┆        ┆            ┆          │
│ 2001-01      ┆ Canada  ┆ 2021A000011 ┆ All sizes   ┆ … ┆ null   ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆ 124         ┆             ┆   ┆        ┆        ┆            ┆          │
│ 2001-01      ┆ Canada  ┆ 2021A000011 ┆ All sizes   ┆ … ┆ null   ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆ 124         ┆             ┆   ┆        ┆        ┆            ┆          │
│ 2001-01      ┆ Canada  ┆ 2021A000011 ┆ All sizes   ┆ … ┆ null   ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆ 124         ┆             ┆   ┆        ┆        ┆            ┆          │
│ 2001-01      ┆ Canada  ┆ 2021A000011 ┆ All sizes   ┆ … ┆ null   ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆ 124         ┆             ┆   ┆        ┆        ┆            ┆          │
│ …            ┆ …       ┆ …           ┆ …           ┆ … ┆ …      ┆ …      ┆ …          ┆ …        │
│ 2024-07      ┆ Nunavut ┆ 2021A000262 ┆ 300 and     ┆ … ┆ x      ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆             ┆ more        ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ employees   ┆   ┆        ┆        ┆            ┆          │
│ 2024-07      ┆ Nunavut ┆ 2021A000262 ┆ 300 and     ┆ … ┆ x      ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆             ┆ more        ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ employees   ┆   ┆        ┆        ┆            ┆          │
│ 2024-07      ┆ Nunavut ┆ 2021A000262 ┆ 300 and     ┆ … ┆ F      ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆             ┆ more        ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ employees   ┆   ┆        ┆        ┆            ┆          │
│ 2024-07      ┆ Nunavut ┆ 2021A000262 ┆ 300 and     ┆ … ┆ x      ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆             ┆ more        ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ employees   ┆   ┆        ┆        ┆            ┆          │
│ 2024-07      ┆ Nunavut ┆ 2021A000262 ┆ 300 and     ┆ … ┆ A      ┆ null   ┆ null       ┆ 2        │
│              ┆         ┆             ┆ more        ┆   ┆        ┆        ┆            ┆          │
│              ┆         ┆             ┆ employees   ┆   ┆        ┆        ┆            ┆          │
└──────────────┴─────────┴─────────────┴─────────────┴───┴────────┴────────┴────────────┴──────────┘

In [61]:
s_df = pl.read_parquet(f'{tables_path}/{table_ids[s_tab_id]}')
s_df

shape: (25, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ Number of  ┆ Unnamed: 1 ┆ Unnamed: 2 ┆ Unnamed:  ┆ Unnamed:  ┆ Unnamed:  ┆ Unnamed:  ┆ Unnamed:  │
│ temporary  ┆ ---        ┆ ---        ┆ 3         ┆ 4         ┆ 5         ┆ 6         ┆ 7         │
│ foreign    ┆ str        ┆ str        ┆ ---       ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ wo…        ┆            ┆            ┆ str       ┆ str       ┆ str       ┆ str       ┆ str       │
│ ---        ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ str        ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ null       ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ null       ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ null       ┆ 2023       ┆ null       ┆ null      ┆ null      ┆ 2024      ┆ null      ┆ null      │
│ Province/T ┆ Jan-Mar    ┆ Apr-Jun    ┆ Jul-Sep   ┆ Oct-Dec   ┆ Jan-Mar   ┆ Apr-Jun   ┆ Jul-Sep   │
│ erritory   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Newfoundla ┆ 599        ┆ 301        ┆ 183       ┆ 869       ┆ 508       ┆ 701       ┆ 750       │
│ nd and     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Labrador   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2. As of   ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ the public ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ ation of   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ Q4…        ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 3. The sum ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ of the     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ number of  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ TF…        ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 4.         ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ Employers  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ may only   ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ submit o…  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 5. The     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ LMIA       ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ System     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ tracks TFW ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ …          ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ 6. The     ┆ null       ┆ null       ┆ null      ┆ null      ┆ null      ┆ null      ┆ null      │
│ numbers    ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ appearing  ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
│ in th…     ┆            ┆            ┆           ┆           ┆           ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

In [62]:
from orqa.utils import sanitize_string

common_cells = list(set(map(sanitize_string, r_df.to_series(r_col_id))) & set(map(sanitize_string, s_df.to_series(s_col_id))))
common_cells

['newfoundland_and_labrador',
 'prince_edward_island',
 'yukon',
 'nunavut',
 'canada',
 'new_brunswick',
 'manitoba',
 'alberta',
 'nova_scotia',
 'ontario',
 'saskatchewan',
 'northwest_territories',
 'british_columbia',
 'quebec']

# Join Evaluation with Agents (Autogen v0.4)

### Agent/wTool Setup

In [ ]:
import asyncio
import json
from dataclasses import dataclass
from typing import List

from autogen_core import (
    AgentId,
    FunctionCall,
    MessageContext,
    RoutedAgent,
    SingleThreadedAgentRuntime,
    message_handler,
)
from autogen_core.models import (
    ChatCompletionClient,
    LLMMessage,
    AssistantMessage,
    SystemMessage,
    UserMessage,
    FunctionExecutionResult, 
    FunctionExecutionResultMessage,
    ModelFamily
)
from autogen_core.tools import FunctionTool, Tool
from autogen_ext.models.ollama import OllamaChatCompletionClient
from autogen_ext.models.openai import OpenAIChatCompletionClient

In [ ]:
@dataclass
class Message:
    content: str


class ToolUseAgent(RoutedAgent):
    def __init__(self, model_client: OpenAIChatCompletionClient|OllamaChatCompletionClient, system_message: str, tool_schema: List[Tool]) -> None:
        super().__init__("JOIN Assistant with Tool")
        self._system_messages: List[LLMMessage] = [
            SystemMessage(content=system_message)
        ]
        self._model_client = model_client
        self._tools = tool_schema

    @message_handler
    async def handle_user_message(self, message: Message, ctx: MessageContext) -> Message:
        # Create a session of messages.
        session: List[LLMMessage] = self._system_messages + [UserMessage(content=message.content, source="user")]

        # Run the chat completion with the tools.
        create_result = await self._model_client.create(
            messages=session,
            tools=self._tools,
            cancellation_token=ctx.cancellation_token,
        )

        # If there are no tool calls, return the result.
        if isinstance(create_result.content, str):
            return Message(content=create_result.content)
        assert isinstance(create_result.content, list) and all(
            isinstance(call, FunctionCall) for call in create_result.content
        )

        # Add the first model create result to the session.
        session.append(AssistantMessage(content=create_result.content, source="assistant"))

        # Execute the tool calls.
        results = await asyncio.gather(
            *[self._execute_tool_call(call, ctx.cancellation_token) for call in create_result.content]
        )

        # Add the function execution results to the session.
        session.append(FunctionExecutionResultMessage(content=results))

        # Run the chat completion again to reflect on the history and function execution results.
        create_result = await self._model_client.create(
            messages=session,
            cancellation_token=ctx.cancellation_token,
        )
        assert isinstance(create_result.content, str)

        # Return the result as a message.
        return Message(content=create_result.content)

    async def _execute_tool_call(
        self, call: FunctionCall, cancellation_token: CancellationToken
    ) -> FunctionExecutionResult:
        # Find the tool by name.
        tool = next((tool for tool in self._tools if tool.name == call.name), None)
        assert tool is not None
        # Run the tool and capture the result.
        try:
            arguments = json.loads(call.arguments)
            result = await tool.run_json(arguments, cancellation_token)
            return FunctionExecutionResult(
                call_id=call.id, content=tool.return_value_as_string(result), is_error=False, name=tool.name
            )
        except Exception as e:
            return FunctionExecutionResult(call_id=call.id, content=str(e), is_error=True, name=tool.name)

In [31]:
from typing import List
from typing_extensions import Annotated
from autogen_core.tools import Tool, FunctionTool

results = []

# in this case prob is not necessary to equip the assistant agent with this tool
# we can simply call it with agent.create()
async def save_join_score(score: Annotated[int, 
                          """A score of the JOIN between 0 and 3 where:
                              0 is CASUAL;
                              1 is SUPERFICIAL;
                              2 is ENGAGED;
                              3 is MEANINGFUL;"""
                          ],
                         explanation: Annotated[str, "A clear, short and concise explanation of the given score"]):
    # print("Tool has been called!")
    results.append((score, explanation))
    return score, explanation

join_score_tool = FunctionTool(save_join_score, description="Save the JOIN evaluation and explanation")

In [85]:
# Create the client
model_client = OllamaChatCompletionClient(
# model_client = OpenAIChatCompletionClient(
    # model="ollama/llama3.3",
    # model="deepseek-r1:70b",
    model="qwq:32b-fp16",
    temperature=0,
    api_key="NotRequiredSinceWeAreLocal",
    base_url="http://localhost:4000",
    model_info={
        "json_output": False,
        "vision": False,
        "function_calling": True,
        # "family": ModelFamily.R1,
        "family": ModelFamily.UNKNOWN,
        "keep_alive": -1
    },
    keep_alive=-1,
    num_ctx=8192
    # options={
    #     "num_ctx": 4096,
    #     "temperature": 0,
    #     "keep_alive": "1h"
    # }
)

system_message = """
    You are a smart AI assistant.
    Do not write code. Do not respond. Only use the provided tool "save_join_score".
"""

# Create a runtime.
runtime = SingleThreadedAgentRuntime()

# Create the tools.
tools: List[Tool] = [join_score_tool]

# Register the agents.
await ToolUseAgent.register(
    runtime,
    "tool_use_agent",
    lambda: ToolUseAgent(
        model_client,
        system_message,
        tools,
    ),
)

AgentType(type='tool_use_agent')

### Agent Interaction

In [76]:
import warnings
warnings.filterwarnings('error')

In [86]:
try:
    runtime.start()
except RuntimeError:
    await runtime.stop()
    runtime.start()

tool_use_agent = AgentId("tool_use_agent", "default")

response = await runtime.send_message(
    Message(f"""
        Define a score for: 
        {r_col_name=}, {s_col_name=}, 
        r_table_name={r_rsc_name}, s_table_name={s_rsc_name}, 
        
        r_table_description={r_pkg_note[:500]}, s_table_description={s_pkg_note[:500]}
        
        common_cells: {common_cells[:30]}
        
        r_table_sample:
        {r_df.sample(5)}, 
        
        s_table_sample:
        {s_df.sample(5)}"""),
    tool_use_agent)
await runtime.stop()

In [87]:
from pprint import pprint
print(response.content)
pprint(results)

<think>
Okay, let's tackle this problem step by step. I need to figure out the correct answer based on the given information. The user has provided details about two tables, r_table and s_table, along with some samples and asks for a score between 0 and 1 indicating their relatedness.

First, let me understand what exactly is being asked here. The task is to determine how related or similar the two tables are, probably based on their structure, content, or the columns they share. The final output should be a numerical score between 0 (not related) and 1 (very related).

Looking at the provided data:

**r_table:**
- Columns include "Number of temporary foreign wo…" and several "Unnamed" columns with numbers. The sample data shows entries like "Alberta" followed by numbers, which might represent counts for different quarters or years. There are also some rows with text explanations, like "2. As of the publication of Q4…" which might be footnotes or additional information. The rows are structured with regions (like provinces) and numerical values across columns.

**s_table:**
- The columns here are more clearly named, with "Number of temporary foreign workers" as the first column, followed by several unnamed columns. The sample shows entries like "Ontario" with numerical data. The structure seems similar to r_table, with regions and numerical values. However, there are also rows with text explanations, like "5. The LMIA System tracks TFW…" and "6. The numbers appearing in th…", which might be footnotes or notes similar to r_table.

Now, to assess the relatedness:

1. **Common Columns or Data Types:**
   Both tables have a column that starts with "Number of temporary foreign workers", which seems to be the main subject. The presence of this column suggests a direct relation. Additionally, both have multiple unnamed columns which likely represent different time periods (quarters or years) with numerical data.

2. **Content Overlap:**
   Both tables list provinces/regions (e.g., Alberta, Nova Scotia, Ontario) followed by numerical data. This indicates they are tracking similar metrics across the same geographic regions. However, the exact time periods might differ, but since the columns are unnamed, it's hard to tell. The presence of similar regions suggests a common subject area.

3. **Footnotes and Structure:**
   Both tables include rows with text explanations (like footnotes 2, 5, 6), which are structured similarly. This could mean they follow the same data format or source, indicating relatedness in their presentation.

4. **Possible Differences:**
   The main difference might be the time frames they cover. For instance, r_table might be for a different set of quarters or years than s_table. Also, the exact metrics might differ slightly (like whether it's "workers" versus another term), but the primary term is similar.

5. **Scoring Consideration:**
   Since the core columns and the structure (regions with numerical data) are the same, the score should be high. However, if there are discrepancies in the time frames or specific metrics not mentioned, it might slightly lower the score. But given the available data, the overlap in subject (temporary foreign workers by region) and structure is strong.

I think the key points here are the shared primary column names (or similar), the use of regions with numerical data across time periods, and the similar footnote structures. These elements strongly indicate a high degree of relatedness. Therefore, the score should be close to 1. Maybe 0.9 or 0.95? But I need to check if there's anything that might reduce the score.

Wait, in the r_table sample, the first entry under "Number of temporary..." is "2. As of the public ation of Q4…", which might be a note, while in s_table, the first data row is "Alberta" with numbers. The presence of notes in both might be a similarity, but maybe they are structured differently. However, the main data rows are comparable.

Another point: the exact column names might differ slightly. The r_table's first column is "Number of temporary foreign wo…" (possibly an abbreviation like "workers" cut off), and s_table's is "Number of temporary foreign workers" fully spelled. That's a minor difference but still very close.

Considering all this, I think the relatedness is very high. So the score should be 1.0? Or maybe 0.95 because there's a slight difference in the column names and possible time frames not matching exactly. But since the user might expect a perfect match if the main elements align, maybe 1.0 is acceptable. Hmm, but perhaps there's a reason to lower it a bit. Let me think again.

Alternatively, maybe the tables are tracking different aspects. For example, one might be about workers and the other about applications or something else. But the column name mentions "workers" directly. The s_table's first column is exactly "Number of temporary foreign workers", while r_table's is similar but cut off. Assuming that's a typo or truncation, they are the same.

Given all these points, I would argue the score is 1.0, but maybe the user expects a slightly lower number. Wait, the problem might be that the tables are actually different. Let me check again the samples:

Looking at the r_table sample:
- The first row under "Number of temporary foreign wo…" has "2. As of the publication of Q4…" which is a note. Then "Alberta" followed by numbers. So the structure is: notes first, then data rows.

In s_table's sample:
- The first data row is "Ontario" with numbers, and then a note like "5. The LMIA System tracks TFW…"

So the order of notes and data might be different, but that's a formatting difference, not content. The actual data rows (regions with numbers) are present in both.

Therefore, the core content is the same, so the relatedness is very high. I think the correct score is 1.0. But maybe the system expects a slightly lower value. Alternatively, perhaps there's a misunderstanding. Let me see if there's any other differences.

Another angle: the "workers" in r_table might refer to something else, but given the context, it's likely the same. The regions are the same, the numerical data structure is the same. Thus, I'll go with 1.0 as the score.
</think>

The two tables, r_table and s_table, are highly related based on their structure, content, and subject matter. Here's the breakdown:

1. **Common Subject and Columns**: Both tables focus on tracking metrics related to **temporary foreign workers**, specifically listing regions (e.g., Alberta, Ontario) followed by numerical values across time periods (likely quarters or years). The primary column names are nearly identical, with r_table's "Number of temporary foreign wo…" likely truncated but referring to the same metric as s_table's "Number of temporary foreign workers".

2. **Data Structure**: Both include:
   - Regions (e.g., provinces) as the first column.
   - Multiple unnamed columns with numerical data, likely representing time-based metrics (e.g., quarterly counts).
   - Footnotes or explanatory text (e.g., "2. As of...", "5. The LMIA System tracks...") formatted similarly, suggesting a shared source or reporting standard.

3. **Key Differences**:
   - Minor differences in column naming (truncated vs. full text).
   - Possible variations in time frames or specific metrics (unspecified in the provided samples).
   - Slight differences in the placement of footnotes (e.g., r_table includes notes first, while s_table intersperses them with data).

4. **Conclusion**: The core purpose, structure, and content of the tables are identical. The differences are superficial (formatting, minor naming, or time-frame specifics) and do not meaningfully impact their relatedness.

**Final Score**: **1.0**
Both tables are nearly identical in purpose, structure, and content, differing only in minor formatting or truncation. They clearly address the same subject (temporary foreign workers by region) and use the same data format.
[(2,
  'The tables have common geographic locations, but the information and '
  'context are different. The first table contains average weekly earnings for '
  'all employees by enterprise size and North American industry, while the '
  'second table provides data on temporary foreign worker positions by '
  'province/territory.'),
 (2,
  "The tables have a common column 'GEO' with matching values, and the table "
  'descriptions are related to economic data, indicating an engaged join.'),
 (2,
  'The tables have some common columns and data types, but the content and '
  'structure are quite different. Table 1 appears to be a dataset about '
  'employers and employees, while Table 2 seems to be related to temporary '
  'foreign workers. The join operation would require careful consideration of '
  'the relationships between the columns and the data types.'),
 (2,
  "The tables have a common column 'GEOGRAPHICAL AREA' which can be used for "
  'joining, and the data types of the columns are compatible for joining. The '
  'tables also contain relevant data that can be meaningfully combined.')]

# Basic Loop

In [10]:
candidates.columns

['r_tab_id',
 's_tab_id',
 'r_col_id',
 's_col_id',
 'r_col_name',
 's_col_name',
 'size_r_col',
 'size_s_col',
 'r_pkg_id',
 's_pkg_id',
 'size_intersection',
 'size_union',
 'jaccard',
 'overlap']

In [ ]:
# Process one row at a time, getting if this is acceptable or note

evaluations = []

for row in candidates.rows():
    r_tab_id, s_tab_id, r_col_id, s_col_id, r_col_name, s_col_name = row[:6]